steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zebra-crossing-simulator:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zebra-crossing-simulator:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'zebra-crossing-simulator'
      - '--image=gcr.io/$PROJECT_ID/zebra-crossing-simulator:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--timeout=3600'
      - '--cpu=2'
      - '--min-instances=0'
      - '--max-instances=10'

images:
  - 'gcr.io/$PROJECT_ID/zebra-crossing-simulator:$COMMIT_SHA'

timeout: '1800s' 